import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { useAppContext } from '../contexts/AppContext';
import { useRouter } from 'next/router';

export default function Home() {
  const { isAuth } = useAppContext();
  const router = useRouter();

  React.useEffect(() => {
    if (!isAuth) router.push('login')
  }, []);

  if (!isAuth) return null;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={() => {
        window.localStorage.removeItem('token');
        router.push('/login');
      }}>Logout</button>

      <main>
        <h1 className={styles.heading}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
